name: cytoself
channels:
  - defaults
dependencies:
  - pip=21.2.2
  - python=3.7.11
  - pip:
    - absl-py==1.0.0
    - astor==0.8.1
    - beautifulsoup4==4.10.0
    - charset-normalizer==2.0.12
    - colorcet==2.0.6
    - cycler==0.11.0
    - cytoself==0.0.1.2
    - filelock==3.6.0
    - gast==0.2.2
    - gdown==4.3.0
    - google-pasta==0.2.0
    - grpcio==1.44.0
    - h5py==2.10.0
    - idna==3.3
    - importlib-metadata==4.11.1
    - joblib==1.0.1
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - kiwisolver==1.3.2
    - llvmlite==0.38.0
    - markdown==3.3.6
    - matplotlib==3.1.3
    - numba==0.55.1
    - numpy==1.21.5
    - opt-einsum==3.3.0
    - pandas==1.3.5
    - param==1.12.0
    - protobuf==3.19.4
    - pyct==0.4.8
    - pynndescent==0.5.6
    - pyparsing==3.0.7
    - pysocks==1.7.1
    - python-dateutil==2.8.2
    - pytz==2021.3
    - requests==2.27.1
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - seaborn==0.10.1
    - six==1.16.0
    - soupsieve==2.3.1
    - tensorboard==1.15.0
    - tensorflow==1.15.3
    - tensorflow-estimator==1.15.1
    - termcolor==1.1.0
    - threadpoolctl==3.1.0
    - tqdm==4.55.1
    - typing-extensions==4.1.1
    - umap-learn==0.5.1
    - urllib3==1.26.8
    - werkzeug==2.0.3
    - wrapt==1.13.3
    - zipp==3.7.0
